# fly.toml app configuration file generated for spring-resume on 2023-08-04T16:25:57+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "spring-resume"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile-prd"
  [build.args]
    VER = "0.0.2"

[http_service]
  internal_port = 8765
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
