# fly.toml app configuration file generated for spring-docker on 2023-08-04T14:02:03+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "spring-docker"
primary_region = "nrt"

[build]
  VER="0.1.1"
[http_service]
  internal_port = 8765
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
